name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 5 AM GMT+1 (4 AM UTC)
  workflow_dispatch:  # Allows manual run from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🧩 Create the Google Service Account JSON file from GitHub Secrets
      - name: Create credentials file
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > linkedin.json

      - name: Run LinkedIn scraper
        run: |
          python your_script_name.py  # <-- change this to your script’s filename

      - name: Clean up credentials
        run: rm linkedin.json
