name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 5 AM GMT+1 (4 AM UTC)
  workflow_dispatch:    # Allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🧩 Create Google Service Account JSON file from secret
      - name: Create credentials file
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > linkedin.json

      - name: Run LinkedIn scraper
        run: python app.py

      - name: Clean up credentials
        run: rm linkedin.json
